name: semver_sherpa
description: CLI to manage SemVer versions and Keep a Changelog updates for Dart/Flutter projects.
version: 1.0.1
homepage: https://github.com/CarlosFAdev/semver_sherpa
repository: https://github.com/CarlosFAdev/semver_sherpa
issue_tracker: https://github.com/CarlosFAdev/semver_sherpa/issues

environment:
  sdk: ^3.11.0

dependencies:
  args: ^2.7.0
  path: ^1.9.1
  process_run: ^1.3.0
  yaml: ^3.1.3

executables:
  semver_sherpa: semver_sherpa

dev_dependencies:
  lints: ^6.1.0
  mocktail: ^1.0.4
  test: ^1.29.0
