name: release_tool
description: CLI to manage SemVer versions and Keep a Changelog updates for Dart/Flutter projects.
version: 0.1.0
homepage: https://github.com/CarlosFAdev/release_tool
repository: https://github.com/CarlosFAdev/release_tool
issue_tracker: https://github.com/CarlosFAdev/release_tool/issues

environment:
  sdk: ^3.11.0

dependencies:
  args: ^2.7.0
  path: ^1.9.1
  process_run: ^1.3.0
  yaml: ^3.1.3

executables:
  release_tool: release_tool

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.29.0
