name: release_tool
description: Professional CLI to manage SemVer versions in Flutter projects
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  args: ^2.7.0
  path: ^1.9.1
  process_run: ^1.3.0
  yaml: ^3.1.3

executables:
  release: release_tool

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.29.0
